apiVersion: v1
kind: ReplicationController
metadata:
  name: myadd-rc
  type: front-end
spec:
  template:
    metadata:
      name: nginx
    spec:
      containers:
      - name: nginx 
        image: nginx
